# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200, unique=True)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackGenereMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackMusic.Genere')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackMusic.Track')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trackgeneremap',
            unique_together=set([('track_id', 'genere_id')]),
        ),
    ]
